var names;
var num;
var married;
var phone;
names = "Samet";
num = 7;
married = false;
phone = "Iphone";
console.log("Phone number: " + phone);
phone = 05554443322;
console.log("Mobile Phone: " + phone);
